language: php
php:
  - 5.4
  - 5.5
before_script:
  - composer install
script:
  - ./bin/behat
  - ./bin/phpspec run -fpretty
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover spec/coverage/clover.xml
notifications:
  email: "mike@crumm.net"